version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: .
    stdin_open: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:4200
